type User {
  id: ID!
  username: String!
  email: String!
  password: String!
  avatarUrl: String
  createdAt: String
  updatedAt: String
  token: String
}

type Avatar {
  id: ID!
  url: String!
  lastModified: String
}

type CreateUserResponse {
  message: String!
  user: User
}

type AvatarResponse {
  message: String!
  avatarUrl:String!
}

type Query {
  login(email: String!, password: String!): CreateUserResponse
}

type Mutation {
  # create user
  createUser(
    username: String!
    email: String!
    password: String!
    avatarUrl: String
  ): CreateUserResponse
  # create avatar
  createAvatar(
    token: String!
    buffer: String!
  ): AvatarResponse
}
